import argparse
import math
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

import cv2
import numpy as np


@dataclass(frozen=True)
class Layout:
    cols: int
    cell: int
    arrow: int
    sep: int
    pad_left: int
    pad_top: int

    @property
    def base_h(self) -> int:
        return 2 * int(self.cell) + int(self.arrow)

    @property
    def content_w(self) -> int:
        return int(self.cols) * int(self.cell) + (int(self.cols) - 1) * int(self.sep)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Extract the bottom-row (inpainted) 3 object images from each assembled template image.\n\n"
            "Assumes templates are generated by assemble_multiview_templates.py (top cell + arrow + bottom cell), "
            "and may be resized by the inpaint model (e.g. 3216x2144 -> 2528x1696)."
        )
    )
    parser.add_argument(
        "--banana_inpaint_dir",
        type=str,
        required=True,
        help="Path to candidate_views/banana_inpaint (contains template images).",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=None,
        help="Where to save crops (default: <banana_inpaint_dir>/bottom_row).",
    )
    parser.add_argument(
        "--cols",
        type=int,
        default=3,
        help="Number of columns (views) in the template (default: 3).",
    )
    parser.add_argument(
        "--cell_size",
        type=int,
        default=1024,
        help="Cell size used when assembling templates (default: 1024).",
    )
    parser.add_argument(
        "--arrow_height",
        type=int,
        default=96,
        help="Arrow separator height used when assembling templates (default: 96).",
    )
    parser.add_argument(
        "--col_padding",
        type=int,
        default=32,
        help="Column padding used when assembling templates (default: 32).",
    )
    parser.add_argument(
        "--col_divider_width",
        type=int,
        default=6,
        help="Column divider width used when assembling templates (default: 6).",
    )
    parser.add_argument(
        "--ext",
        type=str,
        default="png",
        choices=["png", "jpg", "jpeg"],
        help="Output image extension.",
    )
    parser.add_argument(
        "--dry_run",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="If enabled, only print what would be written.",
    )
    return parser.parse_args()


def _sep_width(col_padding: int, col_divider_width: int) -> int:
    divider_w = max(1, int(col_divider_width))
    gap_w = int(col_padding)
    if gap_w <= 0:
        return divider_w
    return max(gap_w, divider_w)


def _safe_round(x: float) -> int:
    return int(max(1, int(round(float(x)))))


def infer_layout(
    *,
    img_w: int,
    img_h: int,
    cols: int,
    cell_size: int,
    arrow_height: int,
    col_padding: int,
    col_divider_width: int,
) -> Layout:
    base_h = 2 * int(cell_size) + int(arrow_height)
    if base_h <= 0:
        raise ValueError("Invalid base height from cell_size/arrow_height")

    # Primary scale comes from height.
    scale_h = float(img_h) / float(base_h)

    sep0 = _sep_width(col_padding=col_padding, col_divider_width=col_divider_width)
    base_content_w = int(cols) * int(cell_size) + (int(cols) - 1) * int(sep0)
    if base_content_w <= 0:
        raise ValueError("Invalid base content width from cols/cell_size/col_padding")

    # If the inferred content width would exceed the actual width, fall back to a width-derived scale.
    scaled_cell_h = _safe_round(int(cell_size) * scale_h)
    scaled_arrow_h = max(1, int(round(int(arrow_height) * scale_h)))
    scaled_sep_h = max(1, int(round(int(sep0) * scale_h)))
    content_w_h = int(cols) * int(scaled_cell_h) + (int(cols) - 1) * int(scaled_sep_h)

    scale = scale_h
    if content_w_h > int(img_w):
        scale_w = float(img_w) / float(base_content_w)
        scale = min(scale_h, scale_w)

    cell = _safe_round(int(cell_size) * scale)
    arrow = max(1, int(round(int(arrow_height) * scale)))
    sep = max(1, int(round(int(sep0) * scale)))

    base_h_scaled = 2 * int(cell) + int(arrow)
    pad_top = max((int(img_h) - int(base_h_scaled)) // 2, 0)

    content_w = int(cols) * int(cell) + (int(cols) - 1) * int(sep)
    pad_left = max((int(img_w) - int(content_w)) // 2, 0)

    return Layout(cols=int(cols), cell=int(cell), arrow=int(arrow), sep=int(sep), pad_left=int(pad_left), pad_top=int(pad_top))


def _iter_images(folder: Path) -> List[Path]:
    exts = {".png", ".jpg", ".jpeg", ".bmp", ".webp"}
    paths = [p for p in folder.iterdir() if p.is_file() and p.suffix.lower() in exts]
    return sorted(paths, key=lambda p: p.name)


def _crop_safe(img: np.ndarray, x0: int, y0: int, w: int, h: int) -> Optional[np.ndarray]:
    ih, iw = int(img.shape[0]), int(img.shape[1])
    x1 = max(0, int(x0))
    y1 = max(0, int(y0))
    x2 = min(iw, int(x0) + int(w))
    y2 = min(ih, int(y0) + int(h))
    if x2 <= x1 or y2 <= y1:
        return None
    return img[y1:y2, x1:x2].copy()


def main() -> int:
    args = parse_args()
    in_dir = Path(args.banana_inpaint_dir)
    if not in_dir.exists():
        print(f"Missing directory: {in_dir}")
        return 2

    out_dir = Path(args.output_dir) if args.output_dir else (in_dir / "bottom_row")
    if not args.dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    images = _iter_images(in_dir)
    if not images:
        print(f"No images found in: {in_dir}")
        return 0

    for path in images:
        img = cv2.imread(str(path), cv2.IMREAD_COLOR)
        if img is None:
            print(f"[Warn] Failed reading: {path}")
            continue

        h, w = int(img.shape[0]), int(img.shape[1])
        layout = infer_layout(
            img_w=w,
            img_h=h,
            cols=int(args.cols),
            cell_size=int(args.cell_size),
            arrow_height=int(args.arrow_height),
            col_padding=int(args.col_padding),
            col_divider_width=int(args.col_divider_width),
        )

        bottom_y0 = int(layout.pad_top) + int(layout.cell) + int(layout.arrow)
        for col in range(int(layout.cols)):
            x0 = int(layout.pad_left) + int(col) * (int(layout.cell) + int(layout.sep))
            crop = _crop_safe(img, x0=x0, y0=bottom_y0, w=int(layout.cell), h=int(layout.cell))
            if crop is None:
                print(f"[Warn] {path.name}: crop out of bounds for col={col+1}")
                continue

            out_path = out_dir / f"{path.stem}_bottom_{col+1:02d}.{str(args.ext).lower()}"
            if args.dry_run:
                print(f"[DryRun] {path.name} -> {out_path.name} (x0={x0}, y0={bottom_y0}, s={layout.cell})")
                continue

            ok = cv2.imwrite(str(out_path), crop)
            if not ok:
                print(f"[Warn] Failed writing: {out_path}")
                continue
        print(f"[OK] {path.name} (w={w}, h={h}, cell={layout.cell}, arrow={layout.arrow}, sep={layout.sep}, pad_left={layout.pad_left}, pad_top={layout.pad_top})")

    print(f"[Done] Output: {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
